n by n Magic Squares

In [2]:
import numpy as np

def generate_magic_square(n):
    if n % 2 == 1:  # Odd order
        return generate_odd_magic_square(n)
    elif n % 4 == 0:  # Doubly even order
        return generate_doubly_even_magic_square(n)
    elif n % 2 == 0 and n % 4 != 0:  # Singly even order
        return generate_singly_even_magic_square(n)
    else:
        raise ValueError("Invalid order for a magic square.")

def generate_odd_magic_square(n):
    """Generate an odd-order magic square using the Siamese method."""
    magic_square = np.zeros((n, n), dtype=int)
    num = 1
    i, j = 0, n // 2

    while num <= n * n:
        magic_square[i, j] = num
        num += 1
        new_i, new_j = (i - 1) % n, (j + 1) % n
        if magic_square[new_i, new_j]:
            i += 1
        else:
            i, j = new_i, new_j

    return magic_square

def generate_doubly_even_magic_square(n):
    """Generate a doubly even magic square (where n is a multiple of 4)."""
    magic_square = np.arange(1, n * n + 1).reshape(n, n)

    for i in range(n):
        for j in range(n):
            if (i % 4 == j % 4) or ((i + j) % 4 == 3):
                magic_square[i, j] = n * n + 1 - magic_square[i, j]

    return magic_square

def generate_singly_even_magic_square(n):
    """Generate a singly even magic square using the Strachey method (where n = 4k + 2)."""
    half_n = n // 2
    sub_square = generate_odd_magic_square(half_n)

    magic_square = np.zeros((n, n), dtype=int)


    magic_square[:half_n, :half_n] = sub_square
    magic_square[:half_n, half_n:] = sub_square + 2 * half_n * half_n
    magic_square[half_n:, :half_n] = sub_square + 3 * half_n * half_n
    magic_square[half_n:, half_n:] = sub_square + half_n * half_n


    cols_to_swap = (n // 2 - 1) // 2


    for i in range(half_n):

        for j in range(cols_to_swap):
            magic_square[i, j], magic_square[i + half_n, j] = magic_square[i + half_n, j], magic_square[i, j]


        magic_square[i, 0], magic_square[i + half_n, 0] = magic_square[i + half_n, 0], magic_square[i, 0]


    for i in range(half_n):
        magic_square[i, -1], magic_square[i + half_n, -1] = magic_square[i + half_n, -1], magic_square[i, -1]

    return magic_square

def check_sums(magic_square):
    """Check and print the sums of rows, columns, and diagonals for inspection."""
    n = magic_square.shape[0]


    row_sums = [np.sum(magic_square[i, :]) for i in range(n)]

    col_sums = [np.sum(magic_square[:, j]) for j in range(n)]

    main_diagonal_sum = np.sum(np.diag(magic_square))

    secondary_diagonal_sum = np.sum(np.diag(np.fliplr(magic_square)))

    print("\nSum of each row:", row_sums)
    print("Sum of each column:", col_sums)
    print("Sum of main diagonal:", main_diagonal_sum)
    print("Sum of secondary diagonal:", secondary_diagonal_sum)

n = int(input("Enter the order of the magic square (n must be greater than or equal to 3): "))

if n < 3:
    print("Order n must be greater than or equal to 3.")
else:
    magic_square = generate_magic_square(n)
    print("\nMagic Square:")
    print(magic_square)
    check_sums(magic_square)


Enter the order of the magic square (n must be greater than or equal to 3): 5

Magic Square:
[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]

Sum of each row: [65, 65, 65, 65, 65]
Sum of each column: [65, 65, 65, 65, 65]
Sum of main diagonal: 65
Sum of secondary diagonal: 65
